service: pixelshrink-lambda

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-south-1

environment:

  ORIGINAL_BUCKET: pixelshrink-original-images
  PROCESSED_BUCKET: pixelshrink-processed-images
  # BACKEND_URL: ${env:BACKEND_URL}
  LAMBDA_SECRET: pixelshrink_lambda_secret_2026

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource:
            - arn:aws:s3:::pixelshrink-original-images/*

        - Effect: Allow
          Action:
            - s3:PutObject
          Resource:
            - arn:aws:s3:::pixelshrink-processed-images/*


functions:
  processImage:
    handler: handler.processImageHandler
